# docker-compose.yml for user-rest-spring-service development
# This provides minimal infrastructure needed for this service

services:
  # Kafka cluster
  kafka:
    image: bitnami/kafka:3.9
    container_name: user-rest-kafka
    ports:
      - "9092:9092"
    environment:
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,PLAINTEXT_HOST://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      - KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_CFG_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=1
      - KAFKA_CFG_TRANSACTION_STATE_LOG_MIN_ISR=1
      - ALLOW_PLAINTEXT_LISTENER=yes
    volumes:
      - kafka_data:/bitnami/kafka
    networks:
      - user-rest-network
    healthcheck:
      test:
        ["CMD", "kafka-topics.sh", "--bootstrap-server", "kafka:9092", "--list"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  # Redis for caching
  redis:
    image: redis:latest
    container_name: user-rest-redis
    ports:
      - "6379:6379"
    networks:
      - user-rest-network
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  # Mock Thrift Server for testing (using WireMock)
  mock-thrift-server:
    image: wiremock/wiremock:latest
    container_name: user-rest-mock-thrift
    ports:
      - "9090:8080"
    volumes:
      - ./docker/wiremock:/home/wiremock
    networks:
      - user-rest-network
    command: --global-response-templating --verbose

  # The main service
  user-rest-spring-service:
    build:
      context: .
      dockerfile: Dockerfile
    image: hzeroxium/user-rest-spring-service:latest
    container_name: user-rest-spring-service
    env_file:
      - .env
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATA_REDIS_URL=redis://redis:6379
      - CACHE_PROVIDER=redis
      - THRIFT_CLIENT_HOST=mock-thrift-server
      - THRIFT_CLIENT_PORT=8080
    volumes:
      - ./logs:/app/logs:rw
    depends_on:
      kafka:
        condition: service_healthy
      redis:
        condition: service_healthy
      mock-thrift-server:
        condition: service_started
    ports:
      - "8080:8080"
    networks:
      - user-rest-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

volumes:
  kafka_data:
  redis_data:

networks:
  user-rest-network:
    driver: bridge
