
services:
  mongodb:
    image: mongo:8.0
    container_name: mongodb
    environment:
      - MONGO_INITDB_DATABASE=users
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - thrift-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    depends_on:
      mongodb:
        condition: service_healthy
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://mongodb:27017/users
      ME_CONFIG_MONGODB_ENABLE_ADMIN: "true"
    networks:
      - thrift-network

  user-rpc-thrift-service:
    build:
      context: ./user-rpc-thrift-service
      dockerfile: Dockerfile
    image: user-rpc-thrift-service:latest
    container_name: user-rpc-thrift-service
    environment:
      - PERSISTENCE_TYPE=mongo
      - SERVER_PORT=8080
      - THRIFT_PORT=9090
      - MONGODB_URI=mongodb://mongodb:27017/users
      - JDBC_URL=jdbc:h2:mem:userdb;DB_CLOSE_DELAY=-1;MODE=LEGACY
    ports:
      - "8080:8080"
      - "9090:9090"
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - thrift-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  user-rest-spring-service:
    build:
      context: ./user-rest-spring-service
      dockerfile: Dockerfile
    image: user-rest-spring-service:latest
    container_name: user-rest-spring-service
    environment:
      - SERVER_PORT=8083
      - THRIFT_HOST=user-rpc-thrift-service
      - THRIFT_PORT=9090
    depends_on:
      user-rpc-thrift-service:
        condition: service_healthy
    ports:
      - "8083:8083"
    networks:
      - thrift-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8083/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

volumes:
  mongodb_data:

networks:
  thrift-network:
    driver: bridge

