services:
  # Consul server for service discovery
  consul:
    image: hashicorp/consul:1.17
    container_name: consul
    ports:
      - "8500:8500"
    environment:
      - CONSUL_BIND_INTERFACE=eth0
    command: >
      consul agent -dev 
      -client=0.0.0.0 
      -ui 
      -log-level=info 
      -data-dir=/consul/data
    healthcheck:
      test: ["CMD", "consul", "members"]
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 10s

  # Config Server
  config-server:
    build:
      context: ./config-server
      dockerfile: Dockerfile
    image: hzeroxium/config-server:latest
    container_name: config-server
    ports:
      - "8888:8888"
    environment:
      # - CONFIG_GIT_URI=file:///app/ztf-spring-cloud-config-server
      - CONFIG_GIT_URI=https://github.com/HZeroxium/ztf-spring-cloud-config-server.git
      - CONFIG_GIT_LABEL=master
      - KAFKA_BROKERS=10.40.30.233:9092
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8888/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Sample Service
  sample-service:
    build:
      context: ./sample-service
      dockerfile: Dockerfile
    image: hzeroxium/sample-service:latest
    container_name: sample-service
    ports:
      - "8080:8080"
    environment:
      - CONFIG_SERVER_URL=http://config-server:8888
      - KAFKA_BROKERS=10.40.30.233:9092
      - SPRING_PROFILES_ACTIVE=dev
      - ZCM_SDK_SERVICE_NAME=sample-service
      - ZCM_SDK_CONFIG_SERVER_URL=http://config-server:8888
      - ZCM_SDK_DISCOVERY_CONSUL_HOST=consul
      - ZCM_SDK_DISCOVERY_CONSUL_HEARTBEAT_ENABLED=true
      - ZCM_SDK_DISCOVERY_CONSUL_REGISTER=true
      - ZCM_SDK_PING_ENABLED=false
      - ZCM_SDK_CONTROL_URL=http://config-control-service:8080
    depends_on:
      config-server:
        condition: service_healthy
      consul:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    stop_grace_period: 30s

  # Scale Sample Service to 3 instances
  sample-service-2:
    build:
      context: ./sample-service
      dockerfile: Dockerfile
    image: hzeroxium/sample-service:latest
    container_name: sample-service-2
    ports:
      - "8082:8080"
    environment:
      - CONFIG_SERVER_URL=http://config-server:8888
      - KAFKA_BROKERS=10.40.30.233:9092
      - SPRING_PROFILES_ACTIVE=dev
      - ZCM_SDK_SERVICE_NAME=sample-service
      - ZCM_SDK_CONFIG_SERVER_URL=http://config-server:8888
      - ZCM_SDK_DISCOVERY_CONSUL_HOST=consul
      - ZCM_SDK_DISCOVERY_CONSUL_HEARTBEAT_ENABLED=true
      - ZCM_SDK_DISCOVERY_CONSUL_REGISTER=true
    depends_on:
      config-server:
        condition: service_healthy
      consul:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    stop_grace_period: 30s

  # # Scale Sample Service to 3 instances
  # sample-service-3:
  #   build:
  #     context: ./sample-service
  #     dockerfile: Dockerfile
  #   image: hzeroxium/sample-service:latest
  #   container_name: config-demo-client-3
  #   ports:
  #     - "8082:8080"
  #   environment:
  #     - CONFIG_SERVER_URL=http://config-server:8888
  #     - KAFKA_BROKERS=kafka:9092
  #     - SPRING_PROFILES_ACTIVE=dev
  #   depends_on:
  #     config-server:
  #       condition: service_healthy
  #     kafka:
  #       condition: service_healthy
  #   healthcheck:
  #     test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
  #     interval: 30s
  #     timeout: 10s
  #     retries: 3


  # Config Control Service
  config-control-service:
    build:
      context: ./config-control-service
      dockerfile: Dockerfile
    image: hzeroxium/config-control-service:latest
    container_name: config-control-service
    ports:
      - "8081:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - CONFIG_SERVER_URL=http://config-server:8888
      - CONSUL_URL=http://consul:8500
      - MONGODB_URI=mongodb://10.40.30.233:27017/config_control
      - REDIS_URL=redis://10.40.30.233:6379
      - KAFKA_BROKERS=10.40.30.233:9092
    depends_on:
      config-server:
        condition: service_healthy
      consul:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  default:
    name: config-demo-network
    driver: bridge


