services:
  # Consul server for service discovery
  consul:
    image: hashicorp/consul:1.17
    container_name: consul
    ports:
      - "8500:8500"
    environment:
      - CONSUL_BIND_INTERFACE=eth0
    command: >
      consul agent -dev 
      -client=0.0.0.0 
      -ui 
      -log-level=info 
      -data-dir=/consul/data
    healthcheck:
      test: ["CMD", "consul", "members"]
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 10s
    # volumes:
    #   - ./data/consul-data:/consul/data

  # Config Server
  config-server:
    build:
      context: ./config-server
      dockerfile: Dockerfile
    image: hzeroxium/config-server:latest
    container_name: config-server
    ports:
      - "8888:8888"
    environment:
      # - CONFIG_GIT_URI=file:///app/ztf-spring-cloud-config-server
      - CONFIG_GIT_URI=https://github.com/HZeroxium/ztf-spring-cloud-config-server.git
      - CONFIG_GIT_LABEL=master
      - KAFKA_BROKERS=10.40.30.233:9092
      - CONSUL_HOST=consul
      - CONSUL_PORT=8500
    depends_on:
      consul:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8888/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Sample Service
  sample-service:
    build:
      context: ./sample-service
      dockerfile: Dockerfile
    image: hzeroxium/sample-service:latest
    container_name: sample-service
    ports:
      - "8080:8080"
    environment:
      - CONFIG_SERVER_URL=http://config-server:8888
      - KAFKA_BROKERS=10.40.30.233:9092
      - SPRING_PROFILES_ACTIVE=dev
      - ZCM_SDK_SERVICE_NAME=sample-service
      - ZCM_SDK_CONFIG_SERVER_URL=http://config-server:8888
      - ZCM_SDK_DISCOVERY_CONSUL_HOST=consul
      - ZCM_SDK_DISCOVERY_CONSUL_HEARTBEAT_ENABLED=true
      - ZCM_SDK_DISCOVERY_CONSUL_REGISTER=true
      - ZCM_SDK_PING_ENABLED=true
      - ZCM_SDK_CONTROL_URL=http://config-control-service:8080
    depends_on:
      config-server:
        condition: service_healthy
      consul:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    stop_grace_period: 30s

  # Scale Sample Service to 3 instances
  sample-service-2:
    build:
      context: ./sample-service
      dockerfile: Dockerfile
    image: hzeroxium/sample-service:latest
    container_name: sample-service-2
    ports:
      - "8082:8080"
    environment:
      - CONFIG_SERVER_URL=http://config-server:8888
      - KAFKA_BROKERS=10.40.30.233:9092
      - SPRING_PROFILES_ACTIVE=dev
      - ZCM_SDK_SERVICE_NAME=sample-service
      - ZCM_SDK_CONFIG_SERVER_URL=http://config-server:8888
      - ZCM_SDK_DISCOVERY_CONSUL_HOST=consul
      - ZCM_SDK_DISCOVERY_CONSUL_HEARTBEAT_ENABLED=true
      - ZCM_SDK_DISCOVERY_CONSUL_REGISTER=true
      - ZCM_SDK_PING_ENABLED=true
      - ZCM_SDK_CONTROL_URL=http://config-control-service:8080
    depends_on:
      config-server:
        condition: service_healthy
      consul:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    stop_grace_period: 30s


  # Config Control Service
  config-control-service:
    build:
      context: ./config-control-service
      dockerfile: Dockerfile
    image: hzeroxium/config-control-service:latest
    container_name: config-control-service
    ports:
      - "8081:8080"    # HTTP
      - "9090:9090"    # Thrift
      - "9091:9091"    # gRPC
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - CONFIG_SERVER_URL=http://config-server:8888
      - CONSUL_URL=http://consul:8500
      - MONGODB_URI=mongodb://10.40.30.233:27017/config_control
      - REDIS_URL=redis://10.40.30.233:6379
      - KAFKA_BROKERS=10.40.30.233:9092
      - THRIFT_PORT=9090
      - GRPC_PORT=9091
    depends_on:
      config-server:
        condition: service_healthy
      consul:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # # etcd for KV Store
  # etcd:
  #   image: quay.io/coreos/etcd:v3.5.12
  #   container_name: etcd
  #   ports:
  #     - "2379:2379"
  #     - "2380:2380"
  #   environment:
  #     - ETCD_NAME=etcd0
  #     - ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379
  #     - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
  #     - ETCD_INITIAL_ADVERTISE_PEER_URLS=http://etcd:2380
  #     - ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380
  #     - ETCD_INITIAL_CLUSTER=etcd0=http://etcd:2380
  #     - ETCD_INITIAL_CLUSTER_TOKEN=etcd-cluster
  #     - ETCD_INITIAL_CLUSTER_STATE=new
  #   healthcheck:
  #     test: ["CMD", "etcdctl", "endpoint", "health"]
  #     interval: 10s
  #     timeout: 3s
  #     retries: 5


networks:
  default:
    name: config-demo-network
    driver: bridge


