# Grafana Tempo Configuration for Distributed Tracing
# Simplified configuration for Tempo v2.9.0 (monolithic mode)

server:
  http_listen_port: 3200
  grpc_listen_port: 9096

distributor:
  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: 0.0.0.0:4317
        http:
          endpoint: 0.0.0.0:4318
    jaeger:
      protocols:
        grpc:
          endpoint: 0.0.0.0:14250
        thrift_http:
          endpoint: 0.0.0.0:14268
        thrift_compact:
          endpoint: 0.0.0.0:6831
        thrift_binary:
          endpoint: 0.0.0.0:6832
    zipkin:
      endpoint: 0.0.0.0:9411

storage:
  trace:
    backend: s3
    s3:
      bucket: tempo-data
      endpoint: minio:9000
      access_key: minioadmin
      secret_key: minioadmin
      insecure: true
      region: us-east-1
    wal:
      path: /var/tempo/wal
    block:
      version: vParquet3

metrics_generator:
  registry:
    external_labels:
      source: tempo
  storage:
    path: /var/tempo/generator/wal
    remote_write:
      - url: http://mimir:9009/api/v1/push
        send_exemplars: true
  traces_storage:
    path: /var/tempo/generator/traces

compactor:
  compaction:
    block_retention: 168h  # 7 days

overrides:
  defaults:
    metrics_generator:
      processors:
        - service-graphs
        - span-metrics
        - local-blocks  # ADD THIS - enables TraceQL metrics and Grafana drill-down
