server:
  port: 8083

spring:
  application:
    name: user-rest-spring-service
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:default}

# Thrift client configuration
thrift:
  host: ${THRIFT_HOST:localhost}
  port: ${THRIFT_PORT:9090}
  timeout: 5000
  retry-attempts: 3

# Application configuration
app:
  name: user-rest-spring-service
  version: 1.0.0
  environment: ${ENVIRONMENT:development}

# Management and monitoring configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics,env,beans,configprops,loggers,threaddump,heapdump
  endpoint:
    health:
      show-details: when_authorized
      show-components: always
    prometheus:
      enabled: true
    metrics:
      enabled: true
  metrics:
    tags:
      application: user-rest-spring-service
      service: user-rest-spring-service
      environment: ${ENVIRONMENT:development}
    export:
      prometheus:
        enabled: true
        step: 10s
    distribution:
      percentiles-histogram:
        http.server.requests: true
        http.client.requests: true
      percentiles:
        http.server.requests: 0.5, 0.9, 0.95, 0.99
        http.client.requests: 0.5, 0.9, 0.95, 0.99
      slo:
        http.server.requests: 50ms, 100ms, 200ms, 500ms, 1s, 2s, 5s
        http.client.requests: 50ms, 100ms, 200ms, 500ms, 1s, 2s, 5s
  tracing:
    sampling:
      probability: 1.0
    zipkin:
      endpoint: http://zipkin:9411/api/v2/spans

# Logging configuration - using Log4j2
logging:
  level:
    com.example.rest: DEBUG
    com.example.user: DEBUG
    org.springframework.web: DEBUG
    org.apache.thrift: DEBUG
    io.micrometer: DEBUG
  config: classpath:log4j2-spring.xml