spring:
  datasource:
    url: ${JDBC_URL:jdbc:h2:mem:userdb;DB_CLOSE_DELAY=-1;MODE=LEGACY}
    driver-class-name: org.h2.Driver
    username: sa
    password: ''
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017/users}

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: when_authorized
  metrics:
    tags:
      application: user-rpc-thrift-service

thrift:
  port: ${THRIFT_PORT:9090}

app:
  persistence:
    type: ${PERSISTENCE_TYPE:mongo} # h2 | mongo
