server:
  port: 8080

spring:
  application:
    name: user-rpc-thrift-service
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:default}
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017/users}
    jpa:
      hibernate:
        ddl-auto: create-drop
      show-sql: false
      properties:
        hibernate:
          format_sql: true
          use_sql_comments: true
      database-platform: org.hibernate.dialect.H2Dialect
  datasource:
    url: ${JDBC_URL:jdbc:h2:mem:userdb;DB_CLOSE_DELAY=-1;MODE=LEGACY}
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  cache:
    cache-names: userById, usersByCriteria, countByCriteria
  autoconfigure:
    exclude: 
      - org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration
      - org.springframework.boot.autoconfigure.data.redis.RedisRepositoriesAutoConfiguration
  
  # Kafka configuration for Workers
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:kafka:9092}
    
    consumer:
      group-id: user-update-workers
      auto-offset-reset: earliest
      enable-auto-commit: false
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        partition.assignment.strategy: org.apache.kafka.clients.consumer.CooperativeStickyAssignor
        # Enhanced connection resilience
        reconnect.backoff.ms: 1000
        reconnect.backoff.max.ms: 10000
        retry.backoff.ms: 1000
        request.timeout.ms: 30000
        session.timeout.ms: 30000
        heartbeat.interval.ms: 10000
        max.poll.interval.ms: 300000
        # Connection pool settings
        connections.max.idle.ms: 540000
        # Security and reliability
        enable.auto.commit: false
        isolation.level: read_committed
    
    listener:
      ack-mode: record
      missing-topics-fatal: false
    
    producer:
      acks: all
      compression-type: snappy
      retries: 2147483647
      properties:
        enable.idempotence: true
        delivery.timeout.ms: 120000
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      # Transactional producer for EOS
      transaction-id-prefix: worker-tx-


# Thrift server configuration
thrift:
  port: ${THRIFT_PORT:9090}

# Application configuration
app:
  name: user-rpc-thrift-service
  version: 1.0.0
  environment: ${ENVIRONMENT:development}
  persistence:
    type: ${PERSISTENCE_TYPE:mongo}

# Management and monitoring configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics,env,beans,configprops,loggers,threaddump,heapdump,cache
  endpoint:
    health:
      show-details: when_authorized
      show-components: always
    prometheus:
      enabled: true
    metrics:
      enabled: true
  metrics:
    enable:
      cache: true
    tags:
      application: user-rpc-thrift-service
      service: user-rpc-thrift-service
      environment: ${ENVIRONMENT:development}
    distribution:
      percentiles-histogram:
        http.server.requests: true
        http.client.requests: true
      percentiles:
        http.server.requests: 0.5, 0.9, 0.95, 0.99
        http.client.requests: 0.5, 0.9, 0.95, 0.99
      slo:
        http.server.requests: 50ms, 100ms, 200ms, 500ms, 1s, 2s, 5s
        http.client.requests: 50ms, 100ms, 200ms, 500ms, 1s, 2s, 5s
  tracing:
    sampling:
      probability: 1.0

# Logging configuration - using Log4j2
logging:
  level:
    com.example.user: DEBUG
    org.springframework.web: DEBUG
    org.apache.thrift: DEBUG
    io.micrometer: DEBUG
  config: classpath:log4j2-spring.xml