/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * Config Control Service API
 * Centralized configuration management and drift detection service.

**Features:**
- Service instance heartbeat tracking
- Configuration drift detection and reporting
- Service discovery integration with Consul
- Config refresh orchestration via Kafka
- Real-time monitoring and alerts

**Architecture:**
- Hexagonal architecture with distinct API, Application, Domain, and Infrastructure layers
- MongoDB for persistence
- Redis for caching
- Kafka for event broadcasting

 * OpenAPI spec version: 1.0.0
 */

/**
 * Service lifecycle stage
 */
export type ApplicationServiceResponseLifecycle = typeof ApplicationServiceResponseLifecycle[keyof typeof ApplicationServiceResponseLifecycle];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ApplicationServiceResponseLifecycle = {
  ACTIVE: 'ACTIVE',
  DEPRECATED: 'DEPRECATED',
  RETIRED: 'RETIRED',
} as const;
