/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * Config Control Service API
 * Centralized configuration management and drift detection service.

**Features:**
- Service instance heartbeat tracking
- Configuration drift detection and reporting
- Service discovery integration with Consul
- Config refresh orchestration via Kafka
- Real-time monitoring and alerts

**Architecture:**
- Hexagonal architecture with distinct API, Application, Domain, and Infrastructure layers
- MongoDB for persistence
- Redis for caching
- Kafka for event broadcasting

 * OpenAPI spec version: 1.0.0
 */
import type { ApplicationServiceCreateRequestAttributes } from './applicationServiceCreateRequestAttributes';

/**
 * Application service creation request
 */
export interface ApplicationServiceCreateRequest {
  /**
   * Unique service identifier
   * @minLength 0
   * @maxLength 100
   */
  id: string;
  /**
   * Human-readable service name
   * @minLength 0
   * @maxLength 200
   */
  displayName: string;
  /**
   * Team that owns this service (null for orphaned services, only SYS_ADMIN can create orphaned)
   * @minLength 0
   * @maxLength 100
   */
  ownerTeamId?: string;
  /**
   * List of environments where this service is deployed (defaults to ["dev", "staging", "prod"] if not provided)
   * @minItems 1
   * @maxItems 2147483647
   */
  environments?: string[];
  /** Optional tags for categorization */
  tags?: string[];
  /**
   * Git repository URL
   * @minLength 0
   * @maxLength 500
   */
  repoUrl?: string;
  /** Additional service attributes */
  attributes?: ApplicationServiceCreateRequestAttributes;
}
