/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * Config Control Service API
 * Centralized configuration management and drift detection service.

**Features:**
- Service instance heartbeat tracking
- Configuration drift detection and reporting
- Service discovery integration with Consul
- Config refresh orchestration via Kafka
- Real-time monitoring and alerts

**Architecture:**
- Hexagonal architecture with distinct API, Application, Domain, and Infrastructure layers
- MongoDB for persistence
- Redis for caching
- Kafka for event broadcasting

 * OpenAPI spec version: 1.0.0
 */
import type { ApplicationServiceUpdateRequestLifecycle } from './applicationServiceUpdateRequestLifecycle';
import type { ApplicationServiceUpdateRequestAttributes } from './applicationServiceUpdateRequestAttributes';

/**
 * Application service update request
 */
export interface ApplicationServiceUpdateRequest {
  /**
   * Human-readable service name
   * @minLength 0
   * @maxLength 200
   */
  displayName?: string;
  /**
   * Service lifecycle stage
   * @minLength 0
   * @maxLength 50
   */
  lifecycle?: ApplicationServiceUpdateRequestLifecycle;
  /** Optional tags for categorization */
  tags?: string[];
  /**
   * Git repository URL
   * @minLength 0
   * @maxLength 500
   */
  repoUrl?: string;
  /** Additional service attributes */
  attributes?: ApplicationServiceUpdateRequestAttributes;
}
