/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * Config Control Service API
 * Centralized configuration management and drift detection service.

**Features:**
- Service instance heartbeat tracking
- Configuration drift detection and reporting
- Service discovery integration with Consul
- Config refresh orchestration via Kafka
- Real-time monitoring and alerts

**Architecture:**
- Hexagonal architecture with distinct API, Application, Domain, and Infrastructure layers
- MongoDB for persistence
- Redis for caching
- Kafka for event broadcasting

 * OpenAPI spec version: 1.0.0
 */
import type { ApprovalDecisionResponseGate } from './approvalDecisionResponseGate';
import type { ApprovalDecisionResponseDecision } from './approvalDecisionResponseDecision';

/**
 * Approval decision details response
 */
export interface ApprovalDecisionResponse {
  /** Unique decision identifier */
  id?: string;
  /** Associated approval request ID */
  requestId?: string;
  /** User who made the decision */
  approverUserId?: string;
  /** Approval gate */
  gate?: ApprovalDecisionResponseGate;
  /** Decision made */
  decision?: ApprovalDecisionResponseDecision;
  /** When the decision was made */
  decidedAt?: string;
  /** Decision notes */
  note?: string;
}
