/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * Config Control Service API
 * Centralized configuration management and drift detection service.

**Features:**
- Service instance heartbeat tracking
- Configuration drift detection and reporting
- Service discovery integration with Consul
- Config refresh orchestration via Kafka
- Real-time monitoring and alerts

**Architecture:**
- Hexagonal architecture with distinct API, Application, Domain, and Infrastructure layers
- MongoDB for persistence
- Redis for caching
- Kafka for event broadcasting

 * OpenAPI spec version: 1.0.0
 */
import type { ApprovalRequestApprovalTarget } from './approvalRequestApprovalTarget';
import type { ApprovalRequestApprovalGate } from './approvalRequestApprovalGate';
import type { ApprovalRequestRequesterSnapshot } from './approvalRequestRequesterSnapshot';
import type { ApprovalRequestResponseCounts } from './approvalRequestResponseCounts';

/**
 * Approval request details response
 */
export interface ApprovalRequestResponse {
  id?: string;
  requesterUserId?: string;
  requestType?: string;
  target?: ApprovalRequestApprovalTarget;
  required?: ApprovalRequestApprovalGate[];
  status?: string;
  snapshot?: ApprovalRequestRequesterSnapshot;
  counts?: ApprovalRequestResponseCounts;
  createdAt?: string;
  updatedAt?: string;
  note?: string;
  cancelReason?: string;
}
