/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * Config Control Service API
 * Centralized configuration management and drift detection service.

**Features:**
- Service instance heartbeat tracking
- Configuration drift detection and reporting
- Service discovery integration with Consul
- Config refresh orchestration via Kafka
- Real-time monitoring and alerts

**Architecture:**
- Hexagonal architecture with distinct API, Application, Domain, and Infrastructure layers
- MongoDB for persistence
- Redis for caching
- Kafka for event broadcasting

 * OpenAPI spec version: 1.0.0
 */
import type { ConfigServerEnvironmentResponseState } from './configServerEnvironmentResponseState';
import type { ConfigServerPropertySource } from './configServerPropertySource';

/**
 * Response containing configuration environment details from Config Server
 */
export interface ConfigServerEnvironmentResponse {
  /** Name of the application requesting configuration */
  name: string;
  /** List of active Spring profiles for this configuration */
  profiles?: string[];
  /** Git label, branch, or tag used for this configuration */
  label?: string;
  /** Git commit SHA or version identifier of the configuration */
  version?: string;
  /** Current state of the configuration */
  state?: ConfigServerEnvironmentResponseState;
  /** Ordered list of property sources, with higher priority sources first */
  propertySources?: ConfigServerPropertySource[];
}
