/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * Config Control Service API
 * Centralized configuration management and drift detection service.

**Features:**
- Service instance heartbeat tracking
- Configuration drift detection and reporting
- Service discovery integration with Consul
- Config refresh orchestration via Kafka
- Real-time monitoring and alerts

**Architecture:**
- Hexagonal architecture with distinct API, Application, Domain, and Infrastructure layers
- MongoDB for persistence
- Redis for caching
- Kafka for event broadcasting

 * OpenAPI spec version: 1.0.0
 */
import type { ConsulHealthCheckStatus } from './consulHealthCheckStatus';
import type { ConsulHealthCheckType } from './consulHealthCheckType';
import type { ConsulHealthCheckDefinition } from './consulHealthCheckDefinition';

/**
 * Health check information with status and timing details
 */
export interface ConsulHealthCheck {
  /** Node name where check runs */
  Node?: string;
  /** Unique check identifier */
  CheckID?: string;
  /** Human-readable check name */
  Name?: string;
  /** Check status */
  Status?: ConsulHealthCheckStatus;
  /** Optional notes about the check */
  Notes?: string;
  /** Check output message */
  Output?: string;
  /** Associated service ID */
  ServiceID?: string;
  /** Associated service name */
  ServiceName?: string;
  /** Tags of the associated service */
  ServiceTags?: string[];
  /** Check type */
  Type?: ConsulHealthCheckType;
  /** Check interval */
  Interval?: string;
  /** Check timeout */
  Timeout?: string;
  /** Exposed port for check */
  ExposedPort?: number;
  /** Check definition details */
  Definition?: ConsulHealthCheckDefinition;
  /** Raft index when check was created */
  CreateIndex?: number;
  /** Raft index when check was last modified */
  ModifyIndex?: number;
}
