/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * Config Control Service API
 * Centralized configuration management and drift detection service.

**Features:**
- Service instance heartbeat tracking
- Configuration drift detection and reporting
- Service discovery integration with Consul
- Config refresh orchestration via Kafka
- Real-time monitoring and alerts

**Architecture:**
- Hexagonal architecture with distinct API, Application, Domain, and Infrastructure layers
- MongoDB for persistence
- Redis for caching
- Kafka for event broadcasting

 * OpenAPI spec version: 1.0.0
 */
import type { ConsulTaggedAddresses } from './consulTaggedAddresses';
import type { ConsulNodeInfoMeta } from './consulNodeInfoMeta';

/**
 * Node information in health check response
 */
export interface ConsulNodeInfo {
  /** Unique node identifier */
  ID?: string;
  /** Node name */
  Node?: string;
  /** Node IP address */
  Address?: string;
  /** Datacenter name */
  Datacenter?: string;
  TaggedAddresses?: ConsulTaggedAddresses;
  /** Node metadata */
  Meta?: ConsulNodeInfoMeta;
  /** Raft index when the node was created */
  CreateIndex?: number;
  /** Raft index when the node was last modified */
  ModifyIndex?: number;
}
