/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * Config Control Service API
 * Centralized configuration management and drift detection service.

**Features:**
- Service instance heartbeat tracking
- Configuration drift detection and reporting
- Service discovery integration with Consul
- Config refresh orchestration via Kafka
- Real-time monitoring and alerts

**Architecture:**
- Hexagonal architecture with distinct API, Application, Domain, and Infrastructure layers
- MongoDB for persistence
- Redis for caching
- Kafka for event broadcasting

 * OpenAPI spec version: 1.0.0
 */
import type { ConsulServiceInfoMeta } from './consulServiceInfoMeta';
import type { ConsulServiceWeights } from './consulServiceWeights';
import type { ConsulServiceProxy } from './consulServiceProxy';
import type { ConsulServiceConnect } from './consulServiceConnect';

/**
 * Service information from Consul health check
 */
export interface ConsulServiceInfo {
  /** Service instance ID */
  ID?: string;
  /** Service name */
  Service?: string;
  /** Service tags */
  Tags?: string[];
  /** Service address */
  Address?: string;
  /** Service metadata */
  Meta?: ConsulServiceInfoMeta;
  /** Service port */
  Port?: number;
  Weights?: ConsulServiceWeights;
  /** Whether tags can be overridden */
  EnableTagOverride?: boolean;
  Proxy?: ConsulServiceProxy;
  Connect?: ConsulServiceConnect;
  /** Peer name for federated setups */
  PeerName?: string;
  /** Raft index when service was created */
  CreateIndex?: number;
  /** Raft index when service was last modified */
  ModifyIndex?: number;
}
