/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * Config Control Service API
 * Centralized configuration management and drift detection service.

**Features:**
- Service instance heartbeat tracking
- Configuration drift detection and reporting
- Service discovery integration with Consul
- Config refresh orchestration via Kafka
- Real-time monitoring and alerts

**Architecture:**
- Hexagonal architecture with distinct API, Application, Domain, and Infrastructure layers
- MongoDB for persistence
- Redis for caching
- Kafka for event broadcasting

 * OpenAPI spec version: 1.0.0
 */

/**
 * Tagged network addresses for different network types (LAN/WAN)
 */
export interface ConsulTaggedAddresses {
  /** LAN address */
  lan?: string;
  /** LAN IPv4 address */
  lan_ipv4?: string;
  /** WAN address */
  wan?: string;
  /** WAN IPv4 address */
  wan_ipv4?: string;
}
