/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * Config Control Service API
 * Centralized configuration management and drift detection service.

**Features:**
- Service instance heartbeat tracking
- Configuration drift detection and reporting
- Service discovery integration with Consul
- Config refresh orchestration via Kafka
- Real-time monitoring and alerts

**Architecture:**
- Hexagonal architecture with distinct API, Application, Domain, and Infrastructure layers
- MongoDB for persistence
- Redis for caching
- Kafka for event broadcasting

 * OpenAPI spec version: 1.0.0
 */
import type { DecisionRequestDecision } from './decisionRequestDecision';

/**
 * Decision data (approve/reject with optional note)
 */
export interface DecisionRequest {
  /**
   * Approval decision
   * @minLength 0
   * @maxLength 20
   */
  decision: DecisionRequestDecision;
  /**
   * Optional note explaining the decision
   * @minLength 0
   * @maxLength 500
   */
  note?: string;
}
