/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * Config Control Service API
 * Centralized configuration management and drift detection service.

**Features:**
- Service instance heartbeat tracking
- Configuration drift detection and reporting
- Service discovery integration with Consul
- Config refresh orchestration via Kafka
- Real-time monitoring and alerts

**Architecture:**
- Hexagonal architecture with distinct API, Application, Domain, and Infrastructure layers
- MongoDB for persistence
- Redis for caching
- Kafka for event broadcasting

 * OpenAPI spec version: 1.0.0
 */
import type { DriftEventResponseSeverity } from './driftEventResponseSeverity';
import type { DriftEventResponseStatus } from './driftEventResponseStatus';

/**
 * Drift event details response
 */
export interface DriftEventResponse {
  /** Unique drift event identifier */
  id?: string;
  /** Name of the service */
  serviceName?: string;
  /** Instance identifier */
  instanceId?: string;
  /** Expected configuration hash */
  expectedHash?: string;
  /** Applied configuration hash */
  appliedHash?: string;
  /** Drift severity level */
  severity?: DriftEventResponseSeverity;
  /** Drift status */
  status?: DriftEventResponseStatus;
  /** When drift was detected */
  detectedAt?: string;
  /** When drift was resolved */
  resolvedAt?: string;
  /** Who detected the drift */
  detectedBy?: string;
  /** Who resolved the drift */
  resolvedBy?: string;
  /** Event notes */
  notes?: string;
}
