/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * Config Control Service API
 * Centralized configuration management and drift detection service.

**Features:**
- Service instance heartbeat tracking
- Configuration drift detection and reporting
- Service discovery integration with Consul
- Config refresh orchestration via Kafka
- Real-time monitoring and alerts

**Architecture:**
- Hexagonal architecture with distinct API, Application, Domain, and Infrastructure layers
- MongoDB for persistence
- Redis for caching
- Kafka for event broadcasting

 * OpenAPI spec version: 1.0.0
 */
import type { ErrorResponseContext } from './errorResponseContext';
import type { ValidationError } from './validationError';

/**
 * Standardized error response following RFC-7807 Problem Details for HTTP APIs
 */
export interface ErrorResponse {
  /** A URI reference that identifies the problem type */
  type?: string;
  /** A short, human-readable summary of the problem type */
  title?: string;
  /** The HTTP status code */
  status?: number;
  /** A human-readable explanation specific to this occurrence of the problem */
  detail?: string;
  /** A URI reference that identifies the specific occurrence of the problem */
  instance?: string;
  /** Timestamp when the error occurred */
  timestamp?: string;
  /** Trace ID for correlation across services */
  traceId?: string;
  /** Additional context about the error */
  context?: ErrorResponseContext;
  /** Validation errors (for validation failures) */
  validationErrors?: ValidationError[];
}
