/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * Config Control Service API
 * Centralized configuration management and drift detection service.

**Features:**
- Service instance heartbeat tracking
- Configuration drift detection and reporting
- Service discovery integration with Consul
- Config refresh orchestration via Kafka
- Real-time monitoring and alerts

**Architecture:**
- Hexagonal architecture with distinct API, Application, Domain, and Infrastructure layers
- MongoDB for persistence
- Redis for caching
- Kafka for event broadcasting

 * OpenAPI spec version: 1.0.0
 */
import type { HeartbeatPayload } from './heartbeatPayload';
import type { FailedHeartbeatResponseStatus } from './failedHeartbeatResponseStatus';

/**
 * Failed heartbeat details response
 */
export interface FailedHeartbeatResponse {
  /** Unique failed heartbeat identifier */
  id?: string;
  /** Name of the service */
  serviceName?: string;
  /** Instance identifier */
  instanceId?: string;
  /** Service ID from ApplicationService */
  serviceId?: string;
  /** Team ID that owns this service */
  teamId?: string;
  /** Environment where the heartbeat originated */
  environment?: string;
  payload?: HeartbeatPayload;
  /** Original Kafka topic name */
  originalTopic?: string;
  /** Original Kafka partition number */
  originalPartition?: number;
  /** Original Kafka offset */
  originalOffset?: number;
  /** Exception message that caused the failure */
  exceptionMessage?: string;
  /** Exception class name */
  exceptionClass?: string;
  /** Number of retry attempts before routing to DLQ */
  retryCount?: number;
  /** Current status */
  status?: FailedHeartbeatResponseStatus;
  /** When the heartbeat first failed and was routed to DLQ */
  firstSeenAt?: string;
  /** When the failed heartbeat was last seen */
  lastSeenAt?: string;
  /** When the failed heartbeat was resolved */
  resolvedAt?: string;
  /** User identifier who resolved the failed heartbeat */
  resolvedBy?: string;
  /** Additional notes or investigation summary */
  notes?: string;
}
