/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * Config Control Service API
 * Centralized configuration management and drift detection service.

**Features:**
- Service instance heartbeat tracking
- Configuration drift detection and reporting
- Service discovery integration with Consul
- Config refresh orchestration via Kafka
- Real-time monitoring and alerts

**Architecture:**
- Hexagonal architecture with distinct API, Application, Domain, and Infrastructure layers
- MongoDB for persistence
- Redis for caching
- Kafka for event broadcasting

 * OpenAPI spec version: 1.0.0
 */
import type { FindAllServiceInstancesStatus } from './findAllServiceInstancesStatus';
import type { FindAllServiceInstancesEnvironment } from './findAllServiceInstancesEnvironment';

export type FindAllServiceInstancesParams = {
/**
 * Filter by service ID
 */
serviceId?: string;
/**
 * Filter by instance ID
 */
instanceId?: string;
/**
 * Filter by instance status
 */
status?: FindAllServiceInstancesStatus;
/**
 * Filter by drift status
 */
hasDrift?: string;
/**
 * Filter by environment
 */
environment?: FindAllServiceInstancesEnvironment;
/**
 * Filter by service version
 */
version?: string;
/**
 * Filter instances seen after this timestamp
 */
lastSeenAtFrom?: string;
/**
 * Filter instances seen before this timestamp
 */
lastSeenAtTo?: string;
/**
 * Zero-based page index (0..N)
 * @minimum 0
 */
page?: number;
/**
 * The size of the page to be returned
 * @minimum 1
 */
size?: number;
/**
 * Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported.
 */
sort?: string[];
};
