/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * Config Control Service API
 * Centralized configuration management and drift detection service.

**Features:**
- Service instance heartbeat tracking
- Configuration drift detection and reporting
- Service discovery integration with Consul
- Config refresh orchestration via Kafka
- Real-time monitoring and alerts

**Architecture:**
- Hexagonal architecture with distinct API, Application, Domain, and Infrastructure layers
- MongoDB for persistence
- Redis for caching
- Kafka for event broadcasting

 * OpenAPI spec version: 1.0.0
 */
import type { FindAllDriftEventsStatus } from './findAllDriftEventsStatus';
import type { FindAllDriftEventsSeverity } from './findAllDriftEventsSeverity';
import type { Pageable } from './pageable';

export type FindAllDriftEventsParams = {
/**
 * Filter by service name
 */
serviceName?: string;
/**
 * Filter by instance ID
 */
instanceId?: string;
/**
 * Filter by drift status
 */
status?: FindAllDriftEventsStatus;
/**
 * Filter by severity level
 */
severity?: FindAllDriftEventsSeverity;
/**
 * Show only unresolved events
 */
unresolvedOnly?: boolean;
/**
 * Pagination parameters (page, size, sort)
 */
pageable: Pageable;
};
