/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * Config Control Service API
 * Centralized configuration management and drift detection service.

**Features:**
- Service instance heartbeat tracking
- Configuration drift detection and reporting
- Service discovery integration with Consul
- Config refresh orchestration via Kafka
- Real-time monitoring and alerts

**Architecture:**
- Hexagonal architecture with distinct API, Application, Domain, and Infrastructure layers
- MongoDB for persistence
- Redis for caching
- Kafka for event broadcasting

 * OpenAPI spec version: 1.0.0
 */
import type { FindAllApplicationServicesLifecycle } from './findAllApplicationServicesLifecycle';

export type FindAllApplicationServicesParams = {
/**
 * Filter by owner team ID
 * @minLength 0
 * @maxLength 100
 */
ownerTeamId?: string;
/**
 * Filter by lifecycle stage
 * @minLength 0
 * @maxLength 50
 */
lifecycle?: FindAllApplicationServicesLifecycle;
/**
 * Filter by tags
 */
tags?: string;
/**
 * Search term for service name or description
 * @minLength 0
 * @maxLength 200
 */
search?: string;
/**
 * Zero-based page index (0..N)
 * @minimum 0
 */
page?: number;
/**
 * The size of the page to be returned
 * @minimum 1
 */
size?: number;
/**
 * Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported.
 */
sort?: string[];
};
