/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * Config Control Service API
 * Centralized configuration management and drift detection service.

**Features:**
- Service instance heartbeat tracking
- Configuration drift detection and reporting
- Service discovery integration with Consul
- Config refresh orchestration via Kafka
- Real-time monitoring and alerts

**Architecture:**
- Hexagonal architecture with distinct API, Application, Domain, and Infrastructure layers
- MongoDB for persistence
- Redis for caching
- Kafka for event broadcasting

 * OpenAPI spec version: 1.0.0
 */
import type { FindAllServiceInstancesStatus } from './findAllServiceInstancesStatus';
import type { Pageable } from './pageable';

export type FindAllServiceInstancesParams = {
/**
 * Filter by service name
 */
serviceName?: string;
/**
 * Filter by instance ID
 */
instanceId?: string;
/**
 * Filter by instance status
 */
status?: FindAllServiceInstancesStatus;
/**
 * Filter by drift status
 */
hasDrift?: boolean;
/**
 * Filter by environment
 */
environment?: string;
/**
 * Filter by service version
 */
version?: string;
/**
 * Pagination parameters (page, size, sort)
 */
pageable: Pageable;
};
