/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * Config Control Service API
 * Centralized configuration management and drift detection service.

**Features:**
- Service instance heartbeat tracking
- Configuration drift detection and reporting
- Service discovery integration with Consul
- Config refresh orchestration via Kafka
- Real-time monitoring and alerts

**Architecture:**
- Hexagonal architecture with distinct API, Application, Domain, and Infrastructure layers
- MongoDB for persistence
- Redis for caching
- Kafka for event broadcasting

 * OpenAPI spec version: 1.0.0
 */

/**
 * Request to generate config files for load test services
 */
export interface GenerateLoadTestRequest {
  /**
   * Number of services to generate
   * @minimum 1
   * @maximum 10000
   */
  numServices: number;
  /**
   * Number of instances per service (for variation)
   * @minimum 1
   * @maximum 100
   */
  instancesPerService: number;
}
