/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * Config Control Service API
 * Centralized configuration management and drift detection service.

**Features:**
- Service instance heartbeat tracking
- Configuration drift detection and reporting
- Service discovery integration with Consul
- Config refresh orchestration via Kafka
- Real-time monitoring and alerts

**Architecture:**
- Hexagonal architecture with distinct API, Application, Domain, and Infrastructure layers
- MongoDB for persistence
- Redis for caching
- Kafka for event broadcasting

 * OpenAPI spec version: 1.0.0
 */

/**
 * Response for config file generation for load test services
 */
export interface GenerateLoadTestResponse {
  /** Total number of services generated */
  totalServices?: number;
  /** Number of services with successful generation */
  successCount?: number;
  /** Number of services with failed generation */
  failureCount?: number;
  /** Total number of files generated */
  totalFilesGenerated?: number;
}
