/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * Config Control Service API
 * Centralized configuration management and drift detection service.

**Features:**
- Service instance heartbeat tracking
- Configuration drift detection and reporting
- Service discovery integration with Consul
- Config refresh orchestration via Kafka
- Real-time monitoring and alerts

**Architecture:**
- Hexagonal architecture with distinct API, Application, Domain, and Infrastructure layers
- MongoDB for persistence
- Redis for caching
- Kafka for event broadcasting

 * OpenAPI spec version: 1.0.0
 */

/**
 * IAM team details response
 */
export interface IamTeamResponse {
  /** Unique team identifier */
  teamId?: string;
  /** Team display name */
  displayName?: string;
  /** List of team member user IDs */
  members?: string[];
  /** Team creation timestamp */
  createdAt?: string;
  /** Team last update timestamp */
  updatedAt?: string;
  /** Last sync timestamp from Keycloak */
  syncedAt?: string;
}
