/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * Config Control Service API
 * Centralized configuration management and drift detection service.

**Features:**
- Service instance heartbeat tracking
- Configuration drift detection and reporting
- Service discovery integration with Consul
- Config refresh orchestration via Kafka
- Real-time monitoring and alerts

**Architecture:**
- Hexagonal architecture with distinct API, Application, Domain, and Infrastructure layers
- MongoDB for persistence
- Redis for caching
- Kafka for event broadcasting

 * OpenAPI spec version: 1.0.0
 */

/**
 * KV entry with metadata
 */
export interface KVEntryResponse {
  /** Relative path of the key */
  path?: string;
  /** Value as base64-encoded string */
  valueBase64?: string;
  /** Modify index for CAS operations */
  modifyIndex?: number;
  /** Create index (when key was first created) */
  createIndex?: number;
  /** Flags (arbitrary metadata) */
  flags?: number;
}
