/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * Config Control Service API
 * Centralized configuration management and drift detection service.

**Features:**
- Service instance heartbeat tracking
- Configuration drift detection and reporting
- Service discovery integration with Consul
- Config refresh orchestration via Kafka
- Real-time monitoring and alerts

**Architecture:**
- Hexagonal architecture with distinct API, Application, Domain, and Infrastructure layers
- MongoDB for persistence
- Redis for caching
- Kafka for event broadcasting

 * OpenAPI spec version: 1.0.0
 */
import type { KVPutRequestEncoding } from './kVPutRequestEncoding';

/**
 * Put request with value and options
 */
export interface KVPutRequest {
  /** Value as string (will be encoded based on encoding field) */
  value: string;
  /** Value encoding: 'base64', 'utf8', or 'raw' (default: utf8) */
  encoding?: KVPutRequestEncoding;
  /** CAS (Compare-And-Set) modify index for conditional update */
  cas?: number;
  /**
   * Flags (arbitrary uint64 metadata)
   * @minimum 0
   */
  flags?: number;
}
