/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * Config Control Service API
 * Centralized configuration management and drift detection service.

**Features:**
- Service instance heartbeat tracking
- Configuration drift detection and reporting
- Service discovery integration with Consul
- Config refresh orchestration via Kafka
- Real-time monitoring and alerts

**Architecture:**
- Hexagonal architecture with distinct API, Application, Domain, and Infrastructure layers
- MongoDB for persistence
- Redis for caching
- Kafka for event broadcasting

 * OpenAPI spec version: 1.0.0
 */
import type { KVTransactionOperationOp } from './kVTransactionOperationOp';
import type { KVTransactionOperationEncoding } from './kVTransactionOperationEncoding';

/**
 * Single transaction operation
 */
export interface KVTransactionOperation {
  /** Operation verb */
  op: KVTransactionOperationOp;
  /** Relative path of the key */
  path: string;
  /** Value payload (required for set operations) */
  value?: string;
  /** Value encoding */
  encoding?: KVTransactionOperationEncoding;
  /**
   * Flags metadata to persist with the key
   * @minimum 0
   */
  flags?: number;
  /** CAS modify index for conditional write/delete */
  cas?: number;
}
