/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * Config Control Service API
 * Centralized configuration management and drift detection service.

**Features:**
- Service instance heartbeat tracking
- Configuration drift detection and reporting
- Service discovery integration with Consul
- Config refresh orchestration via Kafka
- Real-time monitoring and alerts

**Architecture:**
- Hexagonal architecture with distinct API, Application, Domain, and Infrastructure layers
- MongoDB for persistence
- Redis for caching
- Kafka for event broadcasting

 * OpenAPI spec version: 1.0.0
 */

/**
 * Outcome of a single transaction operation
 */
export interface KVTransactionResult {
  /** Relative path of the key */
  path?: string;
  /** Whether the operation succeeded */
  success?: boolean;
  /**
   * Modify index returned by Consul
   * @nullable
   */
  modifyIndex?: number | null;
  /**
   * Message describing the failure, if any
   * @nullable
   */
  message?: string | null;
}
