/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * Config Control Service API
 * Centralized configuration management and drift detection service.

**Features:**
- Service instance heartbeat tracking
- Configuration drift detection and reporting
- Service discovery integration with Consul
- Config refresh orchestration via Kafka
- Real-time monitoring and alerts

**Architecture:**
- Hexagonal architecture with distinct API, Application, Domain, and Infrastructure layers
- MongoDB for persistence
- Redis for caching
- Kafka for event broadcasting

 * OpenAPI spec version: 1.0.0
 */

/**
 * Current user information response
 */
export interface MeResponse {
  /** Unique user identifier */
  userId?: string;
  /** Username */
  username?: string;
  /** User email address */
  email?: string;
  /** User first name */
  firstName?: string;
  /** User last name */
  lastName?: string;
  /** List of team IDs user belongs to */
  teamIds?: string[];
  /** User roles */
  roles?: string[];
  /** Manager user ID */
  managerId?: string;
}
