/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * Config Control Service API
 * Centralized configuration management and drift detection service.

**Features:**
- Service instance heartbeat tracking
- Configuration drift detection and reporting
- Service discovery integration with Consul
- Config refresh orchestration via Kafka
- Real-time monitoring and alerts

**Architecture:**
- Hexagonal architecture with distinct API, Application, Domain, and Infrastructure layers
- MongoDB for persistence
- Redis for caching
- Kafka for event broadcasting

 * OpenAPI spec version: 1.0.0
 */

/**
 * Pagination metadata from Spring Data Page
 */
export interface PageMetadata {
  /** Total number of elements across all pages */
  totalElements?: number;
  /** Total number of pages */
  totalPages?: number;
  /** Current page number (0-based) */
  page?: number;
  /** Number of items per page */
  size?: number;
  /** Whether there are more pages available */
  hasNext?: boolean;
  /** Whether there are previous pages available */
  hasPrevious?: boolean;
  /** Number of elements in current page */
  numberOfElements?: number;
  /** Whether the page is empty */
  empty?: boolean;
  first?: boolean;
  last?: boolean;
}
