/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * Config Control Service API
 * Centralized configuration management and drift detection service.

**Features:**
- Service instance heartbeat tracking
- Configuration drift detection and reporting
- Service discovery integration with Consul
- Config refresh orchestration via Kafka
- Real-time monitoring and alerts

**Architecture:**
- Hexagonal architecture with distinct API, Application, Domain, and Infrastructure layers
- MongoDB for persistence
- Redis for caching
- Kafka for event broadcasting

 * OpenAPI spec version: 1.0.0
 */
import type { PermissionsResponseFeatures } from './permissionsResponseFeatures';
import type { PermissionsResponseActions } from './permissionsResponseActions';

/**
 * User permissions and allowed routes response
 */
export interface PermissionsResponse {
  /** API routes user can access */
  allowedApiRoutes?: string[];
  /** UI routes user can access */
  allowedUiRoutes?: string[];
  /** User roles */
  roles?: string[];
  /** User team memberships */
  teams?: string[];
  /** Feature flags for user */
  features?: PermissionsResponseFeatures;
  /** Actions user can perform */
  actions?: PermissionsResponseActions;
  /** Service IDs owned by user's teams */
  ownedServiceIds?: string[];
  /** Service IDs shared with user */
  sharedServiceIds?: string[];
}
