/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * Config Control Service API
 * Centralized configuration management and drift detection service.

**Features:**
- Service instance heartbeat tracking
- Configuration drift detection and reporting
- Service discovery integration with Consul
- Config refresh orchestration via Kafka
- Real-time monitoring and alerts

**Architecture:**
- Hexagonal architecture with distinct API, Application, Domain, and Infrastructure layers
- MongoDB for persistence
- Redis for caching
- Kafka for event broadcasting

 * OpenAPI spec version: 1.0.0
 */
import type { ResponseLifecycle } from './responseLifecycle';
import type { ResponseAttributes } from './responseAttributes';

/**
 * Application service details response
 */
export interface Response {
  /** Unique service identifier */
  id?: string;
  /** Human-readable service name */
  displayName?: string;
  /** Team that owns this service */
  ownerTeamId?: string;
  /** List of environments where this service is deployed */
  environments?: string[];
  /** Service tags for categorization */
  tags?: string[];
  /** Git repository URL */
  repoUrl?: string;
  /** Service lifecycle stage */
  lifecycle?: ResponseLifecycle;
  /** Service creation timestamp */
  createdAt?: string;
  /** Service last update timestamp */
  updatedAt?: string;
  /** User who created this service */
  createdBy?: string;
  /** Additional service attributes */
  attributes?: ResponseAttributes;
}
