/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * Config Control Service API
 * Centralized configuration management and drift detection service.

**Features:**
- Service instance heartbeat tracking
- Configuration drift detection and reporting
- Service discovery integration with Consul
- Config refresh orchestration via Kafka
- Real-time monitoring and alerts

**Architecture:**
- Hexagonal architecture with distinct API, Application, Domain, and Infrastructure layers
- MongoDB for persistence
- Redis for caching
- Kafka for event broadcasting

 * OpenAPI spec version: 1.0.0
 */
import type { SdkConfigGenerationResponseGeneratedConfig } from './sdkConfigGenerationResponseGeneratedConfig';

/**
 * Response containing generated SDK configuration
 */
export interface SdkConfigGenerationResponse {
  /** Service name */
  serviceName?: string;
  /** Generated SDK configuration as map */
  generatedConfig?: SdkConfigGenerationResponseGeneratedConfig;
  /** Generated SDK configuration as YAML string */
  generatedConfigYaml?: string;
  /** Step-by-step integration instructions */
  integrationSteps?: string[];
  /** Estimated integration time */
  estimatedTime?: string;
  /** Suggestions for optional features */
  suggestions?: string[];
}
