/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * Config Control Service API
 * Centralized configuration management and drift detection service.

**Features:**
- Service instance heartbeat tracking
- Configuration drift detection and reporting
- Service discovery integration with Consul
- Config refresh orchestration via Kafka
- Real-time monitoring and alerts

**Architecture:**
- Hexagonal architecture with distinct API, Application, Domain, and Infrastructure layers
- MongoDB for persistence
- Redis for caching
- Kafka for event broadcasting

 * OpenAPI spec version: 1.0.0
 */
import type { ServiceInstanceUpdateRequestEnvironment } from './serviceInstanceUpdateRequestEnvironment';
import type { ServiceInstanceUpdateRequestStatus } from './serviceInstanceUpdateRequestStatus';
import type { ServiceInstanceUpdateRequestMetadata } from './serviceInstanceUpdateRequestMetadata';

/**
 * Service instance update request
 */
export interface ServiceInstanceUpdateRequest {
  /** Instance host address */
  host?: string;
  /** Instance port number */
  port?: number;
  /** Deployment environment */
  environment?: ServiceInstanceUpdateRequestEnvironment;
  /** Service version */
  version?: string;
  /** Current configuration hash */
  configHash?: string;
  /** Last applied configuration hash */
  lastAppliedHash?: string;
  /** Expected configuration hash */
  expectedHash?: string;
  /** Whether drift is detected */
  hasDrift?: boolean;
  /** Instance status */
  status?: ServiceInstanceUpdateRequestStatus;
  /** Instance metadata */
  metadata?: ServiceInstanceUpdateRequestMetadata;
}
