/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * Config Control Service API
 * Centralized configuration management and drift detection service.

**Features:**
- Service instance heartbeat tracking
- Configuration drift detection and reporting
- Service discovery integration with Consul
- Config refresh orchestration via Kafka
- Real-time monitoring and alerts

**Architecture:**
- Hexagonal architecture with distinct API, Application, Domain, and Infrastructure layers
- MongoDB for persistence
- Redis for caching
- Kafka for event broadcasting

 * OpenAPI spec version: 1.0.0
 */
import type { ServiceInstanceCreateRequestEnvironment } from './serviceInstanceCreateRequestEnvironment';
import type { ServiceInstanceCreateRequestMetadata } from './serviceInstanceCreateRequestMetadata';

/**
 * Service instance creation request
 */
export interface ServiceInstanceCreateRequest {
  /** ID of the service */
  serviceId: string;
  /** Unique instance identifier */
  instanceId: string;
  /** Instance host address */
  host?: string;
  /** Instance port number */
  port?: number;
  /** Deployment environment */
  environment?: ServiceInstanceCreateRequestEnvironment;
  /** Service version */
  version?: string;
  /** Current configuration hash */
  configHash?: string;
  /** Last applied configuration hash */
  lastAppliedHash?: string;
  /** Expected configuration hash */
  expectedHash?: string;
  /** Instance metadata */
  metadata?: ServiceInstanceCreateRequestMetadata;
}
