/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * Config Control Service API
 * Centralized configuration management and drift detection service.

**Features:**
- Service instance heartbeat tracking
- Configuration drift detection and reporting
- Service discovery integration with Consul
- Config refresh orchestration via Kafka
- Real-time monitoring and alerts

**Architecture:**
- Hexagonal architecture with distinct API, Application, Domain, and Infrastructure layers
- MongoDB for persistence
- Redis for caching
- Kafka for event broadcasting

 * OpenAPI spec version: 1.0.0
 */
import type { ServiceShareCreateRequestGrantToType } from './serviceShareCreateRequestGrantToType';

/**
 * Service share creation request
 */
export interface ServiceShareCreateRequest {
  /**
   * Service ID to share
   * @minLength 0
   * @maxLength 100
   */
  serviceId: string;
  /**
   * Type of grantee
   * @minLength 0
   * @maxLength 20
   */
  grantToType: ServiceShareCreateRequestGrantToType;
  /**
   * ID of the grantee (team or user)
   * @minLength 0
   * @maxLength 100
   */
  grantToId: string;
  /**
   * List of permissions to grant
   * @minItems 1
   * @maxItems 2147483647
   */
  permissions: string[];
  /** Environments where permissions apply */
  environments?: string[];
  /** Optional expiration timestamp */
  expiresAt?: string;
}
