/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * Config Control Service API
 * Centralized configuration management and drift detection service.

**Features:**
- Service instance heartbeat tracking
- Configuration drift detection and reporting
- Service discovery integration with Consul
- Config refresh orchestration via Kafka
- Real-time monitoring and alerts

**Architecture:**
- Hexagonal architecture with distinct API, Application, Domain, and Infrastructure layers
- MongoDB for persistence
- Redis for caching
- Kafka for event broadcasting

 * OpenAPI spec version: 1.0.0
 */
import type { ServiceShareResponseGrantToType } from './serviceShareResponseGrantToType';

/**
 * Service share details response
 */
export interface ServiceShareResponse {
  /** Unique share identifier */
  id?: string;
  /** Resource level of the share */
  resourceLevel?: string;
  /** Service ID being shared */
  serviceId?: string;
  /** Type of grantee */
  grantToType?: ServiceShareResponseGrantToType;
  /** ID of the grantee */
  grantToId?: string;
  /** Granted permissions */
  permissions?: string[];
  /** Environments where permissions apply */
  environments?: string[];
  /** User who granted the share */
  grantedBy?: string;
  /** Share creation timestamp */
  createdAt?: string;
  /** Share expiration timestamp */
  expiresAt?: string;
}
