/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * Config Control Service API
 * Centralized configuration management and drift detection service.

**Features:**
- Service instance heartbeat tracking
- Configuration drift detection and reporting
- Service discovery integration with Consul
- Config refresh orchestration via Kafka
- Real-time monitoring and alerts

**Architecture:**
- Hexagonal architecture with distinct API, Application, Domain, and Infrastructure layers
- MongoDB for persistence
- Redis for caching
- Kafka for event broadcasting

 * OpenAPI spec version: 1.0.0
 */
import type { ServiceInstanceResponseEnvironment } from './serviceInstanceResponseEnvironment';
import type { ServiceInstanceResponseStatus } from './serviceInstanceResponseStatus';
import type { ServiceInstanceResponseMetadata } from './serviceInstanceResponseMetadata';

/**
 * Service instance details response
 */
export interface ServiceInstanceResponse {
  /** ID of the service */
  serviceId?: string;
  /** Unique instance identifier */
  instanceId?: string;
  /** Instance host address */
  host?: string;
  /** Instance port number */
  port?: number;
  /** Deployment environment */
  environment?: ServiceInstanceResponseEnvironment;
  /** Service version */
  version?: string;
  /** Current configuration hash */
  configHash?: string;
  /** Last applied configuration hash */
  lastAppliedHash?: string;
  /** Expected configuration hash */
  expectedHash?: string;
  /** Instance status */
  status?: ServiceInstanceResponseStatus;
  /** Last time instance was seen */
  lastSeenAt?: string;
  /** Instance creation timestamp */
  createdAt?: string;
  /** Instance last update timestamp */
  updatedAt?: string;
  /** Instance metadata */
  metadata?: ServiceInstanceResponseMetadata;
  /** Whether drift is detected */
  hasDrift?: boolean;
  /** Timestamp when drift was first detected */
  driftDetectedAt?: string;
}
