/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * Config Control Service API
 * Centralized configuration management and drift detection service.

**Features:**
- Service instance heartbeat tracking
- Configuration drift detection and reporting
- Service discovery integration with Consul
- Config refresh orchestration via Kafka
- Real-time monitoring and alerts

**Architecture:**
- Hexagonal architecture with distinct API, Application, Domain, and Infrastructure layers
- MongoDB for persistence
- Redis for caching
- Kafka for event broadcasting

 * OpenAPI spec version: 1.0.0
 */

/**
 * Request to update config file
 */
export interface UpdateConfigFileRequest {
  /** File content (YAML) */
  content: string;
  /** Optional custom commit message */
  customMessage?: string;
  /** Expected SHA for optimistic locking (optional). If provided and doesn't match current SHA, update will fail with conflict. */
  expectedSha?: string;
}
