/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * Config Control Service API
 * Centralized configuration management and drift detection service.

**Features:**
- Service instance heartbeat tracking
- Configuration drift detection and reporting
- Service discovery integration with Consul
- Config refresh orchestration via Kafka
- Real-time monitoring and alerts

**Architecture:**
- Hexagonal architecture with distinct API, Application, Domain, and Infrastructure layers
- MongoDB for persistence
- Redis for caching
- Kafka for event broadcasting

 * OpenAPI spec version: 1.0.0
 */
import type { UpdateRequestStatus } from './updateRequestStatus';

/**
 * Drift event update request
 */
export interface UpdateRequest {
  /** New drift status */
  status?: UpdateRequestStatus;
  /** Who resolved the drift */
  resolvedBy?: string;
  /** Resolution notes */
  notes?: string;
}
