# spring-boot-admin-server/application.yml

server:
  port: 8083

spring:
  application:
    name: spring-boot-admin-server
  security:
    user:
      name: admin
      password: admin
      roles: ADMIN

# Spring Boot Admin Server Configuration
spring.boot.admin:
  server:
    # Enable all monitoring features
    context-path: /admin
    # Configure client discovery
    instance-proxy:
      ignored-headers: Cookie,Set-Cookie,Authorization
    # Enable comprehensive monitoring
    monitor:
      period: 10s
      status-lifetime: 10s
      info-lifetime: 1m
    # Enable notifications (optional)
    notify:
      mail:
        enabled: false
      slack:
        enabled: false
    # Configure UI
    ui:
      title: "Thrift Demo - Spring Boot Admin"
      brand: "Thrift Demo Monitoring"
      favicon: "assets/img/favicon.png"
      favicon-danger: "assets/img/favicon-danger.png"
      # Show all applications
      show-view: ".*"
      # Customize the view
      external-views:
        - name: "Custom Dashboard"
          url: "/admin/#/applications"
          order: 0

# Management and monitoring configuration
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
      show-components: always
    prometheus:
      enabled: true
    metrics:
      enabled: true
  health:
    defaults:
      enabled: true
  metrics:
    tags:
      application: spring-boot-admin-server
      service: spring-boot-admin-server
      environment: ${ENVIRONMENT:development}
    distribution:
      percentiles-histogram:
        http.server.requests: true
      percentiles:
        http.server.requests: 0.5, 0.9, 0.95, 0.99
      slo:
        http.server.requests: 50ms, 100ms, 200ms, 500ms, 1s, 2s, 5s
  tracing:
    sampling:
      probability: 1.0

# Logging configuration
logging:
  level:
    root: ${LOGGING_LEVEL_ROOT:INFO}
    com.example.admin: ${LOGGING_LEVEL_COM_EXAMPLE_ADMIN:DEBUG}
    de.codecentric.boot.admin: DEBUG
    org.springframework.web: INFO
    io.micrometer: INFO
  config: classpath:log4j2-spring.xml

# Application specific configuration
app:
  name: spring-boot-admin-server
  version: 1.0.0
  environment: ${ENVIRONMENT:development}
