version: "3.8"
services:
  mongo:
    image: mongo:8.0
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: users
  user-thrift:
    build: .
    depends_on:
      - mongo
    environment:
      MONGODB_URI: mongodb://mongo:27017/users
      THRIFT_PORT: 9090
    ports:
      - "8080:8080"
      - "9090:9090"
