# docker-compose.yml

services:
  mongo:
    image: mongo:8.0
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: users
    volumes:
      - mongo-data:/data/db

  mongo-express:
    image: mongo-express:latest
    depends_on:
      - mongo
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://mongo:27017/users

  user-thrift:
    build: .
    depends_on:
      - mongo
    environment:
      MONGODB_URI: mongodb://mongo:27017/users
      THRIFT_PORT: 9090
    ports:
      - "8080:8080"
      - "9090:9090"

volumes:
  mongo-data:
