import type { GridColDef, GridValidRowModel } from "@mui/x-data-grid";
import type { ZodType } from "zod";
import type { ConfigServerEnvironmentResponse } from "./models";

// Custom types that are not generated by OpenAPI
// These are used for frontend-specific type definitions

export type ConfigEnvironmentResponse = ConfigServerEnvironmentResponse;

export type ServiceInstanceSummary = {
  serviceName: string;
  instanceId: string;
  host?: string;
  port?: number;
  status?: string;
  scheme?: string;
  uri?: string;
  healthy?: boolean;
  lastSeenAt?: number;
};

export type ConsulServicesMap = {
  services: Record<string, string[]>;
};

// Type aliases for complex record types
export type AttributeMap = Record<string, string | number | boolean | null>;
export type PermissionMap = Record<string, string[]>;
export type MetadataMap = Record<string, unknown>;
export type PropertySourceMap = Record<string, unknown>;

// Generic table column type with proper typing
export type TableColumn<T extends GridValidRowModel = GridValidRowModel> =
  GridColDef<T>;

// Form validation schema type
export type FormSchema = ZodType;
