// Custom types that are not generated by OpenAPI
// These are used for frontend-specific type definitions

export type ConfigEnvironmentResponse = {
  name: string
  profiles: string[]
  label?: string
  version?: string
  state?: string
  propertySources: { name: string; source: Record<string, unknown> }[]
}

export type ServiceInstanceSummary = {
  serviceName: string
  instanceId: string
  host?: string
  port?: number
  status?: string
  scheme?: string
  uri?: string
  healthy?: boolean
  lastSeenAt?: number
}

export type ConsulServicesMap = {
  services: Record<string, string[]>
}
