package com.example.control.domain;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.LocalDateTime;
import java.util.Map;

/**
 * Domain model representing a runtime instance of a service within the system.
 * <p>
 * Each instance corresponds to a running process registered in service discovery (e.g., Consul, Eureka).
 * The model includes both configuration and runtime metadata, allowing drift detection and health monitoring.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class ServiceInstance {

  /** Logical name of the microservice this instance belongs to. */
  private String serviceName;

  /** Unique instance identifier within the service (e.g., generated by Consul). */
  private String instanceId;

  /** Hostname or IP address of the instance. */
  private String host;

  /** TCP port exposed by the instance. */
  private Integer port;

  /** Active Spring profile or environment name (e.g., dev, staging, prod). */
  private String environment;

  /** Service version reported by the instance. */
  private String version;

  /** Current configuration hash reported by the instance (computed via {@code ConfigHashCalculator}). */
  private String configHash;

  /** Last configuration hash applied from the system of truth (SoT). */
  private String lastAppliedHash;

  /** Current health or drift status of the instance. */
  private InstanceStatus status;

  /** Timestamp of the last heartbeat ("ping") received from this instance. */
  private LocalDateTime lastSeenAt;

  /** Timestamp when the instance record was first created. */
  private LocalDateTime createdAt;

  /** Timestamp of the last update. */
  private LocalDateTime updatedAt;

  /** Arbitrary metadata associated with the instance (from Consul, Eureka, etc.). */
  private Map<String, String> metadata;

  /** Indicates whether configuration drift has been detected. */
  private Boolean hasDrift;

  /** Timestamp when configuration drift was detected. */
  private LocalDateTime driftDetectedAt;

  /**
   * Enumeration representing the operational state of the instance.
   */
  public enum InstanceStatus {
    /** Instance is reachable and healthy. */
    HEALTHY,

    /** Instance failed ping or health check. */
    UNHEALTHY,

    /** Instance has configuration drift (mismatch between applied and expected hash). */
    DRIFT,

    /** Instance state could not be determined. */
    UNKNOWN
  }

  /**
   * Determines whether this instance has drifted configuration.
   *
   * @return {@code true} if drift detected, otherwise {@code false}
   */
  public boolean isDrifted() {
    return Boolean.TRUE.equals(hasDrift);
  }

  /**
   * Marks this instance as drifted, recording detection time and updating status.
   *
   * @param expectedHash the expected configuration hash from the source of truth (Config Server)
   */
  public void markDrift(String expectedHash) {
    this.hasDrift = true;
    this.driftDetectedAt = LocalDateTime.now();
    this.status = InstanceStatus.DRIFT;
    this.configHash = expectedHash;
  }

  /**
   * Clears the drift flag and resets status to {@link InstanceStatus#HEALTHY} if previously marked as DRIFT.
   */
  public void clearDrift() {
    this.hasDrift = false;
    this.driftDetectedAt = null;
    if (this.status == InstanceStatus.DRIFT) {
      this.status = InstanceStatus.HEALTHY;
    }
  }
}
