# config-server/application.yml

server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          # Sử dụng local directory thay vì remote Git
          uri: ${CONFIG_GIT_URI:https://github.com/HZeroxium/ztf-spring-cloud-config-server.git}
          default-label: ${CONFIG_GIT_LABEL:master}
          clone-on-start: false
          timeout: 10
          # Tách config theo thư mục ứng dụng (chuẩn de-facto)
          search-paths: "{application}"
          # Tắt force-pull để tránh lỗi read-only
          force-pull: false
        monitor:
          # Enable file monitoring for local config changes
          enabled: true
          # Enable webhook support
          webhook:
            enabled: true
    
    # Spring Cloud Bus configuration
    bus:
      destination: springCloudBus
    stream:
      kafka:
        binder:
          brokers: ${KAFKA_BROKERS:localhost:9092}

management:
  endpoints:
    web:
      exposure:
        include: "health,info,env,refresh,busrefresh,monitor"
  endpoint:
    health:
      show-details: always
    monitor:
      enabled: true

logging:
  level:
    root: INFO
    org.springframework.cloud.config: DEBUG
    org.springframework.cloud.bus: DEBUG
