# config-server/application.yml

server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          # Use GitHub as Git repository
          uri: ${CONFIG_GIT_URI:https://github.com/HZeroxium/ztf-spring-cloud-config-server.git}
          # Use master branch as default
          default-label: ${CONFIG_GIT_LABEL:master}
          clone-on-start: false
          timeout: 10
          # Split config by application directory (standard de-facto)
          search-paths: "{application}"
          # Disable force-pull to avoid read-only error
          force-pull: false
        # Enable Config Server Monitor for GitHub webhooks
        monitor:
          github:
            enabled: true

    # Consul Discovery configuration
    consul:
      host: ${CONSUL_HOST:localhost}
      port: ${CONSUL_PORT:8500}
      discovery:
        enabled: true
        register: true
        deregister: true
        prefer-ip-address: true
        health-check-interval: 10s
        health-check-timeout: 3s
        health-check-critical-timeout: 30s
        instance-id: ${spring.application.name}:${server.port}
        tags:
          - config-server
          - spring-cloud-config
        metadata:
          version: 1.0.0
          secure: false
    
    # Spring Cloud Bus configuration
    bus:
      destination: springCloudBus
      enabled: true
    stream:
      kafka:
        binder:
          brokers: ${KAFKA_BROKERS:localhost:9092}

management:
  endpoints:
    web:
      exposure:
        include: "health,info,env,refresh,busrefresh"
      base-path: /actuator
  endpoint:
    health:
      show-details: always
  security:
    enabled: false

logging:
  level:
    root: INFO
    org.springframework.cloud.config: DEBUG
    org.springframework.cloud.bus: DEBUG
