package com.example.rest.user.mapper;

import com.example.common.domain.SortCriterion;
import com.example.common.domain.User;
import com.example.common.domain.UserQueryCriteria;
import com.example.rest.user.dto.*;

import java.util.List;
import java.util.stream.Collectors;

/** Utility mapping functions between REST DTOs and domain model. */
public final class UserMapper {
  private UserMapper() {}

  /**
   * Map {@link CreateUserRequest} to domain {@link User}.
   *
   * @param req create request payload
   * @return domain user
   */
  public static User toDomainFromCreateRequest(CreateUserRequest req) {
    return User.builder()
        .id(null) // Will be generated by service
        .name(req.getName())
        .phone(req.getPhone())
        .address(req.getAddress())
        .status(req.getStatus() != null ? req.getStatus() : User.UserStatus.ACTIVE)
        .role(req.getRole() != null ? req.getRole() : User.UserRole.USER)
        .createdAt(null) // Will be set by service
        .createdBy("admin")
        .updatedAt(null) // Will be set by service
        .updatedBy("admin")
        .version(1)
        .deleted(false)
        .deletedAt(null)
        .deletedBy(null)
        .build();
  }

  /**
   * Map {@link UpdateUserRequest} to domain {@link User}.
   *
   * @param req update request payload
   * @return domain user
   */
  public static User toDomainFromUpdateRequest(UpdateUserRequest req) {
    return toDomainFromUpdateRequest(req, null);
  }
  
  /**
   * Map {@link UpdateUserRequest} to domain {@link User}.
   *
   * @param req update request payload
   * @param id user id
   * @return domain user
   */
  public static User toDomainFromUpdateRequest(UpdateUserRequest req, String id) {
    return User.builder()
        .id(id)
        .name(req.getName())
        .phone(req.getPhone())
        .address(req.getAddress())
        .status(req.getStatus() != null ? req.getStatus() : User.UserStatus.ACTIVE)
        .role(req.getRole() != null ? req.getRole() : User.UserRole.USER)
        .createdAt(null) // Will be preserved from existing user
        .createdBy(null) // Will be preserved from existing user
        .updatedAt(null) // Will be set by service
        .updatedBy("admin")
        .version(req.getVersion() != null ? req.getVersion() : 1)
        .deleted(false)
        .deletedAt(null)
        .deletedBy(null)
        .build();
  }

  /** Map domain {@link User} to API {@link UserResponse}. */
  public static UserResponse toResponse(User user) {
    return UserResponse.builder()
        .id(user.getId())
        .name(user.getName())
        .phone(user.getPhone())
        .address(user.getAddress())
        .status(user.getStatus())
        .role(user.getRole())
        .createdAt(user.getCreatedAt())
        .createdBy(user.getCreatedBy())
        .updatedAt(user.getUpdatedAt())
        .updatedBy(user.getUpdatedBy())
        .version(user.getVersion())
        .build();
  }

  /**
   * Set the ID of the user.
   *
   * @param user user
   * @param id id
   * @return user with id
   */
  public static User withId(User user, String id) {
    return User.builder()
        .id(id)
        .name(user.getName())
        .phone(user.getPhone())
        .address(user.getAddress())
        .status(user.getStatus())
        .role(user.getRole())
        .createdAt(user.getCreatedAt())
        .createdBy(user.getCreatedBy())
        .updatedAt(user.getUpdatedAt())
        .updatedBy(user.getUpdatedBy())
        .version(user.getVersion())
        .deleted(user.getDeleted())
        .deletedAt(user.getDeletedAt())
        .deletedBy(user.getDeletedBy())
        .build();
  }

  /**
   * Map {@link ListUsersRequest} to domain {@link UserQueryCriteria}.
   *
   * @param req list request payload
   * @return query criteria
   */
  public static UserQueryCriteria toQueryCriteria(ListUsersRequest req) {
    List<SortCriterion> sortCriteria = null;
    
    if (req.getSortCriteria() != null && !req.getSortCriteria().isEmpty()) {
      sortCriteria = req.getSortCriteria().stream()
          .filter(sc -> sc.isValid())  // Only include valid sort criteria
          .map(dto -> SortCriterion.builder()
              .fieldName(dto.getFieldName())
              .direction(dto.getDirection())
              .build())
          .collect(Collectors.toList());
    }
    
    return UserQueryCriteria.builder()
        .page(req.getPage())
        .size(req.getSize())
        .search(req.getSearch())
        .status(req.getStatus())
        .role(req.getRole())
        .includeDeleted(req.getIncludeDeleted() != null ? req.getIncludeDeleted() : false)
        .createdAfter(req.getCreatedAfter())
        .createdBefore(req.getCreatedBefore())
        .sortCriteria(sortCriteria)
        .build();
  }
}


